name: CI Docker

on:
  push:
    branches: [ "main", "preprod", "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Vérifier PHP
        run: php -l index.php

      - name: Build image Docker
        run: docker build -t projet-php .