name: CI simple

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Afficher message
        run: echo "Mon pipeline marche "
